# Generated by Django 5.0.1 on 2024-04-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customuser_email_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='graphDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lable', models.CharField(max_length=100)),
                ('views', models.IntegerField()),
            ],
        ),
    ]
