# Generated by Django 5.0.1 on 2024-04-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_graphdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphdetails',
            old_name='views',
            new_name='customerCount',
        ),
        migrations.RenameField(
            model_name='graphdetails',
            old_name='lable',
            new_name='month',
        ),
        migrations.AddField(
            model_name='graphdetails',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
