# Generated by Django 5.0.1 on 2024-04-21 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_products_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='productPhotos/brakoli_4DRjXUJ.jpg', null=True, upload_to='productPhotos'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_purches',
            field=models.IntegerField(default=0),
        ),
    ]
