# Generated by Django 5.0.1 on 2024-04-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_products_date_posted_alter_customuser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphdetails',
            name='productCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='graphdetails',
            name='customerCount',
            field=models.IntegerField(default=0),
        ),
    ]
