# Generated by Django 5.0.1 on 2024-05-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_graphdetails_productcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_cart',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
