# Generated by Django 5.0.1 on 2024-05-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartbox',
            old_name='product_id',
            new_name='product_id1',
        ),
        migrations.RenameField(
            model_name='cartbox',
            old_name='user_name',
            new_name='user_name1',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
    ]
