# Generated by Django 5.0.1 on 2024-05-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
