# Generated by Django 5.0.1 on 2024-05-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0027_usermessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('sendDate', models.DateField(auto_now_add=True)),
                ('city', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('profilePhoto', models.CharField(max_length=200)),
            ],
        ),
    ]
