# Generated by Django 5.0.1 on 2024-05-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0028_farmerrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerrequests',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
