# Generated by Django 5.0.1 on 2024-05-08 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0029_alter_farmerrequests_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerrequests',
            old_name='province',
            new_name='innerCity',
        ),
    ]
