# Generated by Django 5.0.1 on 2024-05-08 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0030_rename_province_farmerrequests_innercity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerrequests',
            old_name='region',
            new_name='province',
        ),
    ]
