# Generated by Django 5.0.1 on 2024-05-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0031_rename_region_farmerrequests_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerrequests',
            name='first_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
