# Generated by Django 5.0.1 on 2024-05-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0032_farmerrequests_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerrequests',
            name='isConsiderd',
            field=models.BooleanField(default=False),
        ),
    ]
