# Generated by Django 5.0.1 on 2024-05-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0033_farmerrequests_isconsiderd'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphdetails',
            name='farmerRequestsCount',
            field=models.IntegerField(default=0),
        ),
    ]
